use crate::cfg::guards::{FactConfidence, InstructionAnalysisContext, SymbolId};
use serde::{Deserialize, Serialize};

pub mod dominance;
pub mod epic_sec_001;
pub mod resolver;

pub use dominance::DominanceChecker;
pub use epic_sec_001::OwnerValidationRule;
pub use resolver::SymbolResolver;

/// Represents the severity levels for findings generated by the rule engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum RuleSeverity {
    Warning,
    Medium,
    High,
    Critical,
}

/// Structured location of a finding in the source code.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct FindingLocation {
    pub file: String,
    pub line: usize,
    pub column: usize,
    pub node_id: usize,
    pub statement_index: Option<usize>,
}

/// The diagnostic output model representing a security finding.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuleDiagnostic {
    pub rule_id: String,
    pub severity: RuleSeverity,
    pub message: String,
    pub location: FindingLocation,
    pub confidence: FactConfidence,
    pub target_symbol: SymbolId,
}

/// Interface for all EPIC security rules.
pub trait Rule: Send + Sync {
    /// Return the static canonical rule identifier (e.g., "EPIC-SEC-001").
    fn id(&self) -> &'static str;
    /// Return the human-readable description of the rule.
    fn name(&self) -> &'static str;
    /// Run the rule check against the instruction context.
    fn check(
        &self,
        context: &InstructionAnalysisContext,
        resolver: &SymbolResolver,
        dom_checker: &DominanceChecker,
    ) -> Vec<RuleDiagnostic>;
}

/// Executes all registered rules against analysis contexts.
pub struct RuleEngine {
    rules: Vec<Box<dyn Rule>>,
}

impl RuleEngine {
    pub fn new() -> Self {
        Self { rules: Vec::new() }
    }

    pub fn register_rule(&mut self, rule: Box<dyn Rule>) {
        self.rules.push(rule);
    }

    pub fn run_all(&self, context: &InstructionAnalysisContext) -> Vec<RuleDiagnostic> {
        let resolver = SymbolResolver::new(context);
        let dom_checker = DominanceChecker::new(&context.cfg);

        let mut diagnostics = Vec::new();
        for rule in &self.rules {
            diagnostics.extend(rule.check(context, &resolver, &dom_checker));
        }
        diagnostics
    }
}
